# Azure pipeline for Python project
trigger:
- azure-pipelines

pr: none

stages:
- stage: Testing my awesome Python app
  displayName: 'Python matrix testing'
  jobs:
    - job: Unittesting
      pool:
        vmImage: 'Ubuntu-16.04'
      strategy:
        matrix:
          Python36:
            python.version: '3.6'
          Python37:
            python.version: '3.7'
        maxParallel: 2 

      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '$(python.version)'
            architecture: 'x64'

        - script: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
          displayName: 'Install dependencies'
