trigger:
  - azure-pipelines
  - master 

jobs:
  - job: Ubuntu_unit_test
      # https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#pool
    pool:
        vmImage: 'Ubuntu-16.04'
    
    steps:
      - script: echo "Hello world"
        displayName: Hello_world