#  using templates for the pipeline

jobs:

- job:
  displayName: Anaconda_ubuntu
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'

  # using template
  steps:
    - template: ./-anaconda.yml


- job:
  displayName: MacOS_test
  pool:
    vmImage: 'macOS-10.13'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
  
  steps:
    - template: ./anaconda.yml